name: RPi_GPIO_LED_Driver_Pipeline

# Trigger the pipeline on push events
on: [push]

# Work that will be executed when the pipeline is triggered
jobs:
  style_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download checkpatch.pl
        run: |
          wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/checkpatch.pl
          chmod +x checkpatch.pl

      - name: Run kernel style check
        run: |
          ./checkpatch.pl --strict --no-tree --file kernel_module/hello.c